import { Prisma } from "@mensaly/database";
import { BadRequestException, Inject, Injectable, NotFoundException } from "@nestjs/common";
import { PrismaService } from "../infrastructure/database/prisma.service";
import type { AuthenticatedContext } from "../authorization/authorization-context";
import type { CreateEnrollmentInput, CreateGuardianInput, CreatePlanInput, CreateStudentInput, UpdateEnrollmentInput, UpdateGuardianInput, UpdatePlanInput, UpdateStudentInput } from "./operational.dto";

function org(auth: AuthenticatedContext): string { if (!auth.organizationId) throw new NotFoundException({ code: "ORGANIZATION_NOT_FOUND", message: "Organization context is required" }); return auth.organizationId; }
function missing(): never { throw new NotFoundException({ code: "RESOURCE_NOT_FOUND", message: "Resource was not found" }); }
function phone(value: string | undefined) { return value?.replace(/\D/g, ""); }
function tax(value: string | undefined) { return value?.replace(/\D/g, ""); }

@Injectable()
export class OperationalService {
  constructor(@Inject(PrismaService) private readonly prisma: PrismaService) {}
  async plans(auth: AuthenticatedContext, query: { page?: string; pageSize?: string; status?: string }) { const organizationId=org(auth); const page=Math.max(1,Number(query.page??1)); const take=Math.min(100,Math.max(1,Number(query.pageSize??20))); const where={organizationId,...(query.status==="ACTIVE"||query.status==="INACTIVE"?{status:query.status}: {})} as Prisma.PlanWhereInput; const [items,total]=await Promise.all([this.prisma.client.plan.findMany({where,skip:(page-1)*take,take,orderBy:{createdAt:"desc"}}),this.prisma.client.plan.count({where})]); return {items,page,pageSize:take,total}; }
  async plan(auth: AuthenticatedContext,id:string){const item=await this.prisma.client.plan.findFirst({where:{id,organizationId:org(auth)}}); return item??missing();}
  async createPlan(auth: AuthenticatedContext,input:CreatePlanInput){const organizationId=org(auth); return this.prisma.client.plan.create({data:{organizationId,...input}})}
  async updatePlan(auth: AuthenticatedContext,id:string,input:UpdatePlanInput){await this.plan(auth,id); return this.prisma.client.plan.update({where:{id},data:input})}
  async students(auth: AuthenticatedContext,query:Record<string,string|undefined>){const organizationId=org(auth);const page=Math.max(1,Number(query.page??1));const take=Math.min(100,Math.max(1,Number(query.pageSize??20)));const where={organizationId,...(query.status==="ACTIVE"||query.status==="INACTIVE"?{status:query.status}:{}),...(query.search?{name:{contains:String(query.search),mode:"insensitive" as const}}:{})} as Prisma.StudentWhereInput;const [items,total]=await Promise.all([this.prisma.client.student.findMany({where,skip:(page-1)*take,take,orderBy:{createdAt:"desc"}}),this.prisma.client.student.count({where})]);return{items,page,pageSize:take,total};}
  async student(auth:AuthenticatedContext,id:string){const item=await this.prisma.client.student.findFirst({where:{id,organizationId:org(auth)},include:{guardianLinks:{where:{active:true},include:{guardian:true}},enrollments:true}});return item??missing();}
  async createStudent(auth:AuthenticatedContext,input:CreateStudentInput){return this.prisma.client.student.create({data:{organizationId:org(auth),...input,phone:phone(input.phone)}})}
  async updateStudent(auth:AuthenticatedContext,id:string,input:UpdateStudentInput){await this.student(auth,id);return this.prisma.client.student.update({where:{id},data:{...input,phone:input.phone===undefined?undefined:phone(input.phone)}})}
  async guardians(auth:AuthenticatedContext,query:Record<string,string|undefined>){const organizationId=org(auth);return this.prisma.client.guardian.findMany({where:{organizationId,...(query.status==="ACTIVE"||query.status==="INACTIVE"?{status:query.status}:{})} as Prisma.GuardianWhereInput,orderBy:{createdAt:"desc"}})}
  async guardian(auth:AuthenticatedContext,id:string){const item=await this.prisma.client.guardian.findFirst({where:{id,organizationId:org(auth)},include:{studentLinks:{include:{student:true}}}});return item??missing();}
  async createGuardian(auth:AuthenticatedContext,input:CreateGuardianInput){return this.prisma.client.guardian.create({data:{organizationId:org(auth),...input,phone:phone(input.phone)!,taxId:tax(input.taxId)}})}
  async updateGuardian(auth:AuthenticatedContext,id:string,input:UpdateGuardianInput){await this.guardian(auth,id);return this.prisma.client.guardian.update({where:{id},data:{...input,phone:input.phone===undefined?undefined:phone(input.phone),taxId:input.taxId===undefined?undefined:tax(input.taxId)}})}
  async linkGuardian(auth:AuthenticatedContext,studentId:string,guardianId:string,relationship?:string){const organizationId=org(auth);const [student,guardian]=await Promise.all([this.prisma.client.student.findFirst({where:{id:studentId,organizationId}}),this.prisma.client.guardian.findFirst({where:{id:guardianId,organizationId}})]);if(!student||!guardian) return missing();return this.prisma.client.studentGuardian.create({data:{organizationId,studentId,guardianId,relationship}})}
  async enrollments(auth:AuthenticatedContext){return this.prisma.client.enrollment.findMany({where:{organizationId:org(auth)},include:{student:true,guardian:true,plan:true},orderBy:{createdAt:"desc"}})}
  async enrollment(auth:AuthenticatedContext,id:string){const item=await this.prisma.client.enrollment.findFirst({where:{id,organizationId:org(auth)},include:{student:true,guardian:true,plan:true}});return item??missing();}
  async createEnrollment(auth:AuthenticatedContext,input:CreateEnrollmentInput){const organizationId=org(auth);const [student,guardian,plan]=await Promise.all([this.prisma.client.student.findFirst({where:{id:input.studentId,organizationId,status:"ACTIVE"}}),this.prisma.client.guardian.findFirst({where:{id:input.guardianId,organizationId,status:"ACTIVE"}}),this.prisma.client.plan.findFirst({where:{id:input.planId,organizationId,status:"ACTIVE"}})]);if(!student||!guardian||!plan) return missing();const linked=await this.prisma.client.studentGuardian.findFirst({where:{organizationId,studentId:student.id,guardianId:guardian.id,active:true}});if(!linked)throw new BadRequestException({code:"GUARDIAN_LINK_REQUIRED",message:"Guardian must be linked to the student"});return this.prisma.client.enrollment.create({data:{organizationId,...input,amountCents:input.amountCents??plan.amountCents,dueDay:input.dueDay??plan.dueDay,planNameSnapshot:plan.name,startDate:new Date(input.startDate),...(input.endDate?{endDate:new Date(input.endDate)}:{})}})}
  async updateEnrollment(auth:AuthenticatedContext,id:string,input:UpdateEnrollmentInput){await this.enrollment(auth,id);return this.prisma.client.enrollment.update({where:{id},data:{...input,...(input.endDate?{endDate:new Date(input.endDate)}:{})}})}
}
