import { AuditActorType, Prisma } from "@mensaly/database";
import { BadRequestException, Inject, Injectable, NotFoundException } from "@nestjs/common";
import { PrismaService } from "../infrastructure/database/prisma.service";
import type { AuthenticatedContext } from "../authorization/authorization-context";
import type { CreateEnrollmentInput, CreateGuardianInput, CreatePlanInput, CreateStudentInput, EnrollmentListInput, OperationalListInput, UpdateEnrollmentInput, UpdateGuardianInput, UpdatePlanInput, UpdateStudentInput } from "./operational.dto";

function org(auth: AuthenticatedContext): string { if (!auth.organizationId) throw new NotFoundException({ code: "ORGANIZATION_NOT_FOUND", message: "Organization context is required" }); return auth.organizationId; }
function missing(): never { throw new NotFoundException({ code: "RESOURCE_NOT_FOUND", message: "Resource was not found" }); }
function phone(value: string | undefined) { return value?.replace(/\D/g, ""); }
function tax(value: string | undefined) { return value?.replace(/\D/g, ""); }

@Injectable()
export class OperationalService {
  constructor(@Inject(PrismaService) private readonly prisma: PrismaService) {}
  private async audit(auth: AuthenticatedContext, action: string, entityType: string, entityId: string, organizationId: string): Promise<void> { await this.prisma.client.auditLog.create({ data: { organizationId, actorUserId: auth.userId, actorType: AuditActorType.USER, action, entityType, entityId } }); }
  async plans(auth: AuthenticatedContext, query: OperationalListInput) { const organizationId=org(auth); const where={organizationId,...(query.status==="ACTIVE"||query.status==="INACTIVE"?{status:query.status}: {})} as Prisma.PlanWhereInput; const [items,total]=await Promise.all([this.prisma.client.plan.findMany({where,skip:(query.page-1)*query.pageSize,take:query.pageSize,orderBy:{createdAt:"desc"}}),this.prisma.client.plan.count({where})]); return {items,page:query.page,pageSize:query.pageSize,total}; }
  async plan(auth: AuthenticatedContext,id:string){const item=await this.prisma.client.plan.findFirst({where:{id,organizationId:org(auth)}}); return item??missing();}
  async createPlan(auth: AuthenticatedContext,input:CreatePlanInput){const organizationId=org(auth); const item=await this.prisma.client.plan.create({data:{...input,organizationId}});await this.audit(auth,"plan.created","Plan",item.id,organizationId);return item}
  async updatePlan(auth: AuthenticatedContext,id:string,input:UpdatePlanInput){await this.plan(auth,id); const item=await this.prisma.client.plan.update({where:{id},data:input});await this.audit(auth,"plan.updated","Plan",id,org(auth));return item}
  async students(auth: AuthenticatedContext,query:OperationalListInput){const organizationId=org(auth);const where={organizationId,...(query.status==="ACTIVE"||query.status==="INACTIVE"?{status:query.status}:{}),...(query.search?{name:{contains:query.search,mode:"insensitive" as const}}:{})} as Prisma.StudentWhereInput;const [items,total]=await Promise.all([this.prisma.client.student.findMany({where,skip:(query.page-1)*query.pageSize,take:query.pageSize,orderBy:{createdAt:"desc"}}),this.prisma.client.student.count({where})]);return{items,page:query.page,pageSize:query.pageSize,total};}
  async student(auth:AuthenticatedContext,id:string){const item=await this.prisma.client.student.findFirst({where:{id,organizationId:org(auth)},include:{guardianLinks:{where:{active:true},include:{guardian:true}},enrollments:true}});return item??missing();}
  async createStudent(auth:AuthenticatedContext,input:CreateStudentInput){const organizationId=org(auth);const item=await this.prisma.client.student.create({data:{...input,organizationId,phone:phone(input.phone)}});await this.audit(auth,"student.created","Student",item.id,organizationId);return item}
  async updateStudent(auth:AuthenticatedContext,id:string,input:UpdateStudentInput){await this.student(auth,id);const item=await this.prisma.client.student.update({where:{id},data:{...input,phone:input.phone===undefined?undefined:phone(input.phone)}});await this.audit(auth,"student.updated","Student",id,org(auth));return item}
  async guardians(auth:AuthenticatedContext,query:OperationalListInput){const organizationId=org(auth);const where={organizationId,...(query.status==="ACTIVE"||query.status==="INACTIVE"?{status:query.status}:{})} as Prisma.GuardianWhereInput;const [items,total]=await Promise.all([this.prisma.client.guardian.findMany({where,skip:(query.page-1)*query.pageSize,take:query.pageSize,orderBy:{createdAt:"desc"}}),this.prisma.client.guardian.count({where})]);return{items,page:query.page,pageSize:query.pageSize,total};}
  async guardian(auth:AuthenticatedContext,id:string){const item=await this.prisma.client.guardian.findFirst({where:{id,organizationId:org(auth)},include:{studentLinks:{include:{student:true}}}});return item??missing();}
  async createGuardian(auth:AuthenticatedContext,input:CreateGuardianInput){const organizationId=org(auth);const item=await this.prisma.client.guardian.create({data:{...input,organizationId,phone:phone(input.phone)!,taxId:tax(input.taxId)}});await this.audit(auth,"guardian.created","Guardian",item.id,organizationId);return item}
  async updateGuardian(auth:AuthenticatedContext,id:string,input:UpdateGuardianInput){await this.guardian(auth,id);const item=await this.prisma.client.guardian.update({where:{id},data:{...input,phone:input.phone===undefined?undefined:phone(input.phone),taxId:input.taxId===undefined?undefined:tax(input.taxId)}});await this.audit(auth,"guardian.updated","Guardian",id,org(auth));return item}
  async linkGuardian(auth:AuthenticatedContext,studentId:string,guardianId:string,relationship?:string){const organizationId=org(auth);const [student,guardian]=await Promise.all([this.prisma.client.student.findFirst({where:{id:studentId,organizationId}}),this.prisma.client.guardian.findFirst({where:{id:guardianId,organizationId}})]);if(!student||!guardian) return missing();const item=await this.prisma.client.studentGuardian.create({data:{organizationId,studentId,guardianId,relationship}});await this.audit(auth,"student_guardian.created","StudentGuardian",item.id,organizationId);return item}
  async enrollments(auth:AuthenticatedContext,query:EnrollmentListInput){const organizationId=org(auth);const where={organizationId,...(query.status?{status:query.status}: {})} as Prisma.EnrollmentWhereInput;const [items,total]=await Promise.all([this.prisma.client.enrollment.findMany({where,include:{student:true,guardian:true,plan:true},skip:(query.page-1)*query.pageSize,take:query.pageSize,orderBy:{createdAt:"desc"}}),this.prisma.client.enrollment.count({where})]);return{items,page:query.page,pageSize:query.pageSize,total};}
  async enrollment(auth:AuthenticatedContext,id:string){const item=await this.prisma.client.enrollment.findFirst({where:{id,organizationId:org(auth)},include:{student:true,guardian:true,plan:true}});return item??missing();}
  async createEnrollment(auth:AuthenticatedContext,input:CreateEnrollmentInput){const organizationId=org(auth);const [student,guardian,plan]=await Promise.all([this.prisma.client.student.findFirst({where:{id:input.studentId,organizationId,status:"ACTIVE"}}),this.prisma.client.guardian.findFirst({where:{id:input.guardianId,organizationId,status:"ACTIVE"}}),this.prisma.client.plan.findFirst({where:{id:input.planId,organizationId,status:"ACTIVE"}})]);if(!student||!guardian||!plan) return missing();const linked=await this.prisma.client.studentGuardian.findFirst({where:{organizationId,studentId:student.id,guardianId:guardian.id,active:true}});if(!linked)throw new BadRequestException({code:"GUARDIAN_LINK_REQUIRED",message:"Guardian must be linked to the student"});const item=await this.prisma.client.enrollment.create({data:{...input,organizationId,amountCents:input.amountCents??plan.amountCents,dueDay:input.dueDay??plan.dueDay,planNameSnapshot:plan.name,startDate:new Date(input.startDate),...(input.endDate?{endDate:new Date(input.endDate)}:{})}});await this.audit(auth,"enrollment.created","Enrollment",item.id,organizationId);return item}
  async updateEnrollment(auth:AuthenticatedContext,id:string,input:UpdateEnrollmentInput){await this.enrollment(auth,id);const item=await this.prisma.client.enrollment.update({where:{id},data:{...input,...(input.endDate?{endDate:new Date(input.endDate)}:{})}});await this.audit(auth,"enrollment.updated","Enrollment",id,org(auth));return item}
}
