import { Body, Controller, Get, Inject, Param, Patch, Post, Query, UseGuards } from "@nestjs/common";
import { ApiTags } from "@nestjs/swagger";
import { CurrentAuth, type AuthenticatedContext } from "../authorization/authorization-context";
import { CompanyAccountGuard, SessionAuthGuard } from "../authorization/authorization.guards";
import { CreateEnrollmentDto, CreateGuardianDto, CreatePlanDto, CreateStudentDto, UpdateEnrollmentDto, UpdateGuardianDto, UpdatePlanDto, UpdateStudentDto, type CreateEnrollmentInput, type CreateGuardianInput, type CreatePlanInput, type CreateStudentInput, type UpdateEnrollmentInput, type UpdateGuardianInput, type UpdatePlanInput, type UpdateStudentInput } from "./operational.dto";
import { OperationalService } from "./operational.service";
@ApiTags("Operational CRUD") @Controller({path:"",version:"1"}) @UseGuards(SessionAuthGuard,CompanyAccountGuard)
export class OperationalController { constructor(@Inject(OperationalService)private readonly s:OperationalService){}
@Get("plans") plans(@CurrentAuth()a:AuthenticatedContext,@Query()q:Record<string,string|undefined>){return this.s.plans(a,q)} @Post("plans") createPlan(@CurrentAuth()a:AuthenticatedContext,@Body()i:CreatePlanDto){return this.s.createPlan(a,i as unknown as CreatePlanInput)} @Get("plans/:id") plan(@CurrentAuth()a:AuthenticatedContext,@Param("id")id:string){return this.s.plan(a,id)} @Patch("plans/:id") updatePlan(@CurrentAuth()a:AuthenticatedContext,@Param("id")id:string,@Body()i:UpdatePlanDto){return this.s.updatePlan(a,id,i as unknown as UpdatePlanInput)}
@Get("students") students(@CurrentAuth()a:AuthenticatedContext,@Query()q:Record<string,string|undefined>){return this.s.students(a,q)} @Post("students") createStudent(@CurrentAuth()a:AuthenticatedContext,@Body()i:CreateStudentDto){return this.s.createStudent(a,i as unknown as CreateStudentInput)} @Get("students/:id") student(@CurrentAuth()a:AuthenticatedContext,@Param("id")id:string){return this.s.student(a,id)} @Patch("students/:id") updateStudent(@CurrentAuth()a:AuthenticatedContext,@Param("id")id:string,@Body()i:UpdateStudentDto){return this.s.updateStudent(a,id,i as unknown as UpdateStudentInput)} @Post("students/:studentId/guardians/:guardianId") link(@CurrentAuth()a:AuthenticatedContext,@Param("studentId")s:string,@Param("guardianId")g:string,@Body()i:{relationship?:string}){return this.s.linkGuardian(a,s,g,i.relationship)}
@Get("guardians") guardians(@CurrentAuth()a:AuthenticatedContext,@Query()q:Record<string,string|undefined>){return this.s.guardians(a,q)} @Post("guardians") createGuardian(@CurrentAuth()a:AuthenticatedContext,@Body()i:CreateGuardianDto){return this.s.createGuardian(a,i as unknown as CreateGuardianInput)} @Get("guardians/:id") guardian(@CurrentAuth()a:AuthenticatedContext,@Param("id")id:string){return this.s.guardian(a,id)} @Patch("guardians/:id") updateGuardian(@CurrentAuth()a:AuthenticatedContext,@Param("id")id:string,@Body()i:UpdateGuardianDto){return this.s.updateGuardian(a,id,i as unknown as UpdateGuardianInput)}
@Get("enrollments") enrollments(@CurrentAuth()a:AuthenticatedContext,@Query()q:Record<string,string|undefined>){return this.s.enrollments(a,q)} @Post("enrollments") createEnrollment(@CurrentAuth()a:AuthenticatedContext,@Body()i:CreateEnrollmentDto){return this.s.createEnrollment(a,i as unknown as CreateEnrollmentInput)} @Get("enrollments/:id") enrollment(@CurrentAuth()a:AuthenticatedContext,@Param("id")id:string){return this.s.enrollment(a,id)} @Patch("enrollments/:id") updateEnrollment(@CurrentAuth()a:AuthenticatedContext,@Param("id")id:string,@Body()i:UpdateEnrollmentDto){return this.s.updateEnrollment(a,id,i as unknown as UpdateEnrollmentInput)} }
